# Site settings
author: Dmitri Samoterssov
title: Flatiron Journey
header-img: img/home-bg.png
email: dimasamo96@gmail.com
copyright_name: Dmitri Samoterssov
description: > # this means to ignore newlines until "baseurl:"
  My journey of going through the Flatiron coding bootcamp.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  DimaSamo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
